"""add user

Revision ID: 463336e8f29a
Revises: afa3bee6f7d0
Create Date: 2024-03-09 00:41:25.351580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463336e8f29a'
down_revision = 'afa3bee6f7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('user')
    # ### end Alembic commands ###
