"""Description of migration

Revision ID: 8d01ddc9ad1c
Revises: d3ee932d1979
Create Date: 2024-03-01 23:19:13.549256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d01ddc9ad1c'
down_revision = 'd3ee932d1979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner')
    op.drop_table('car')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.Column('producer', sa.VARCHAR(length=100), nullable=False),
    sa.Column('production_year', sa.INTEGER(), nullable=False),
    sa.Column('horsepower', sa.INTEGER(), nullable=False),
    sa.Column('drive', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fuel', sa.VARCHAR(length=100), nullable=False),
    sa.Column('color', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gearbox', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
