"""Initial migration

Revision ID: d3ee932d1979
Revises: 
Create Date: 2024-03-01 22:25:41.632277

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd3ee932d1979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.Column('producer', sa.VARCHAR(length=100), nullable=False),
    sa.Column('production_year', sa.INTEGER(), nullable=False),
    sa.Column('horsepower', sa.INTEGER(), nullable=False),
    sa.Column('drive', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fuel', sa.VARCHAR(length=100), nullable=False),
    sa.Column('color', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gearbox', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
